<?php
/**
 * @file
 * Code for the Stalkerspace module.
 */

/**
 * Implements hook_menu
 */
function stalkerspace_menu() {
  $items = array();
  $items['admin/config/system/stalkerspace'] = array(
    'title' => 'Stalkerspace',
    'description' => 'Access administrative pages for Stalkerspace',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stalkerspace_admin_page'),
    'file' => 'stalkerspace.admin.inc',
    'access arguments' => array('administer stalkerspace'),
    'weight' => -10,
  );

  return $items;
}

/**
 * Implements hook_permissions
 */
function stalkerspace_permission() {
  return array(
    'administer stalkerspace' => array(
      'title' => t('Stalkerspace'),
      'description' => t('Allows administrative access to stalkerspace settings'),
    ),
  );
}

/**
 * Implements hook_init
 */
function stalkerspace_init() {
  $path_alias = drupal_get_path_alias();

  $include_pages = variable_get('ip_geoloc_include_pages', '*');
  if (drupal_match_path($path_alias, $include_pages)) {
    drupal_add_js(drupal_get_path('module', 'stalkerspace') . '/stalkerspace_geolocation.js', 'file');
  }
}

/**
 * Implements hook_form_FORM_ID_alter
 */
function stalkerspace_form_confession_node_form_alter(&$form, &$form_state, $form_id) {
  $query = drupal_get_query_parameters();
  if ($query['space']) {
    // They're radios right now so don't need to do array of default values
    $form['og_group_ref']['und'][0]['default']['#default_value'] = $query['space'];
  }
}

/**
 * Implements hook_block_info
 */
function stalkerspace_block_info() {
  $blocks = array();
  $blocks['stalkerspace_create_content'] = array(
    'info' => t('Stalkerspace Create Content Links'),
    'cache' => DRUPAL_CACHE_PER_ROLE, 
    // Consider DRUPAL_CACHE_PER_PAGE
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function stalkerspace_block_view($delta = '') {
  $block = array();
  $context = og_context();
// Alter access to be only those users in the group (and admin?)
// Otherwise perhaps offer the ability to join the group

  switch ($delta) {
    case 'stalkerspace_create_content':
      $block['subject'] = '';
      $block['content'] = l(t('Confess'), 'node/add/confession', array('html' => FALSE, 'query' => array('space' => $context['gid'])));
    break;
  }

  return $block;
}
